# Generated by Django 6.0.2 on 2026-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('predicted_label', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
