# Generated by Django 6.0.2 on 2026-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsprediction',
            options={},
        ),
        migrations.AlterField(
            model_name='newsprediction',
            name='predicted_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newsprediction',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
