# Generated by Django 6.0.2 on 2026-03-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_newsprediction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsprediction',
            name='confidence_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='fact_check_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='verification_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
